import Head from 'next/head';
import styles from '../styles/Home.module.css';

import Navbar from '../components/navbar/Navbar';
import Banner from '../components/banner/Banner';
import CardSection from '../components/card/CardSection';

const Home = () => {
  const stabVideos = [
    {
      imgUrl: '/static/fallback-card-image.jpg',
    },
    {
      imgUrl: '/static/fallback-card-image.jpg',
    },
    {
      imgUrl: '/static/fallback-card-image.jpg',
    },
    {
      imgUrl: '/static/fallback-card-image.jpg',
    },
  ];

  return (
    <div className={styles.container}>
      <Head>
        <title>Paradiso</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar username="bob@gmail.com" />

      <Banner
        title="Batman"
        subTitle="The Dark Knight"
        imgUrl="/static/banner.jpg"
      />

      <div className={styles.sectionWrapper}>
        <CardSection title="Pixar" videos={stabVideos} size="large" />
      </div>
    </div>
  );
};

export default Home;
