import Head from 'next/head';

import Navbar from '../components/navbar/Navbar';
import Banner from '../components/banner/Banner';
import CardSection from '../components/card/CardSection';
import styles from '../styles/Home.module.css';

import {
  getVideos,
  getPopularVideos,
  getWatchItAgainVideos,
} from '../lib/videos';

import redirectUser from '../utils/redirectUser';

export async function getServerSideProps(context) {
  const { userId, token } = await redirectUser(context);

  if (!userId) {
    return {
      props: {},
      redirect: {
        destination: '/login',
        permanent: false,
      },
    };
  }

  const [
    newMovies,
    travelVideos,
    movieClassic,
    popularVideos,
    watchItAgainVideos,
  ] = await Promise.all([
    getVideos('new movie and tv series official trailer'),
    getVideos('travel videos'),
    getVideos('buster keaton charlie chaplin full movie hd'),
    getPopularVideos(),
    getWatchItAgainVideos(userId, token),
  ]);

  return {
    props: {
      newMovies,
      movieClassic,
      travelVideos,
      popularVideos,
      watchItAgainVideos,
    },
  };
}

const Home = ({
  newMovies,
  movieClassic,
  travelVideos,
  popularVideos,
  watchItAgainVideos,
}) => (
  <div className={styles.container}>
    <Head>
      <title>Paradiso</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <Navbar />

    <main className={styles.main}>
      <Banner
        videoId="Qz3u06eXf0E"
        title="Better Call Saul"
        subTitle="S'all Good, Man"
        imgUrl="/static/banner.jpg"
      />

      <div className={styles.sectionWrapper}>
        <CardSection
          title="New movie and TV series"
          videos={newMovies}
          size="large"
        />

        {watchItAgainVideos.length > 0 && (
          <CardSection
            title="Watch it again"
            videos={watchItAgainVideos}
            size="small"
          />
        )}

        <CardSection
          title="Movie Classic"
          videos={movieClassic}
          size="medium"
        />

        <CardSection title="Travel" videos={travelVideos} size="small" />
        <CardSection title="Popular" videos={popularVideos} size="small" />
      </div>
    </main>
  </div>
);

export default Home;
