import Head from 'next/head';
import styles from '../styles/Home.module.css';

import Navbar from '../components/navbar/Navbar';
import Banner from '../components/banner/Banner';

const Home = () => (
  <div className={styles.container}>
    <Head>
      <title>Paradiso</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <Navbar username="bob@gmail.com" />

    <Banner
      title="Batman"
      subTitle="The Dark Knight"
      imgUrl="/static/banner.jpg"
    />
  </div>
);

export default Home;
